const router = require("express").Router();
const userCtrl = require("../controllers/userCtrl");
const auth = require("../middleware/auth");
router.get("/infor", auth, userCtrl.getUser);
router.post("/register", userCtrl.register);
router.get("/refreshtoken", userCtrl.refreshToken);
router.post("/login", userCtrl.login);
router.get("/logout", userCtrl.logout);
router.patch("/addcart", auth, userCtrl.addCart);
router.get("/history", auth, userCtrl.history);
module.exports = router;
